version: "3.8"

volumes:
  node_modules:

services:
  web:
    build: .
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app # ホストの全体をマウント
      - node_modules:/app/node_modules
